### ISSUE TITLE
active-win is getting the incorrect path on Windows electron build

### ISSUE THREAD

**Issue by whaleprophet** [sindresorhus/get-windows#140]
I'm currently using active-win in an electron app using electron-builder.
I already had the issue of Windows builds breaking because of a mismatched node version, but that was solved by adding 
```postinstall: electron-builder install-app-deps``` instead of `electron-rebuild`.

But its intermittently importing active-win from `app.asar/node_module/active-win` instead of `app.asar.unpacked/node_module/active-win` (though in the app.asar.unpacked folder does have active-win)

Any ideas of using `electron-builder` instead of `electron-rebuild`?

**Comment by sindresorhus** [comment]
This would be a question for the Electron support forums. It's not specific to this package.
