### ISSUE TITLE
I am getting this error after I Forked repo and installed in my electron app

### ISSUE THREAD

**Issue by raghavnaphade** [sindresorhus/get-windows#168]
Error: spawn /Users/path-to-project/node_modules/active-win/main ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /Users/path-to-project/node_modules/active-win/main',
  path: '/Users/path-to-project/mico_wml/node_modules/active-win/main',
  spawnargs: [],
  cmd: '/Users/path-to-project/mico_wml/node_modules/active-win/main',
  stdout: '',
  stderr: ''
}

**Comment by pie6k** [comment]
Does it happen in production or dev or both? If in prod, make sure you properly configured your build pipeline to include all needed binaries outside of '.asar' file
