### ISSUE TITLE
Support of Node 14

### ISSUE THREAD

**Issue by Mrgove10** [sindresorhus/get-windows#72]
Hello, 
Is there any plans to support node 14 ?
https://github.com/sindresorhus/active-win/issues/71 had an issue with v14 too.
No rush, just to know if it was planned 😊

**Comment by FlisherOfatale** [comment]
Anyone know what would be required for it to work in Node v14? Since this is the new LTS version I would prefer to jump on 14 for my new project, which require to have accedd to the active-windows title and other information :)

**Comment by QimatLuo** [comment]
I got the same issue.

**Comment by sharmavivek223** [comment]
Yes, this would be appreciated.

**Comment by sindresorhus** [comment]
This package now targets Node.js 18.
